apiVersion: v1
kind: Service
metadata:
  annotations:
    cm-enabled: 'false'
    cm-intervalSeconds: '30'
  labels:
    app: printall
  name: printall-1
  namespace: te
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: printall
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cm-enabled: 'false'
    cm-intervalSeconds: '30'
  labels:
    app: printall
  name: printall-2
  namespace: te
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: printall
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cm-enabled: 'false'
    cm-intervalSeconds: '30'
  labels:
    app: printall
  name: printall-3
  namespace: te
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: printall
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cm-enabled: 'false'
    cm-intervalSeconds: '30'
  labels:
    app: printall
  name: printall-4
  namespace: te
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: printall
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cm-enabled: 'false'
    cm-intervalSeconds: '30'
  labels:
    app: printall
  name: printall-5
  namespace: te
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: printall
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cm-enabled: 'false'
    cm-intervalSeconds: '30'
  labels:
    app: printall
  name: printall-6
  namespace: te
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: printall
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cm-enabled: 'false'
    cm-intervalSeconds: '30'
  labels:
    app: printall
  name: printall-7
  namespace: te
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: printall
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
